### ISSUE TITLE
German translation

### ISSUE THREAD

**Issue by anderl1969** [bartbutenaers/node-red-contrib-compass#1]
Could you please add a german translation?
`module.exports = {
    descriptions: {
        "N":     "Nord",
        "NNE":   "Nord-Nordost",
        "NE":    "Nordost",
        "ENE":   "Ost-Nordost",
        "E":     "Ost",
        "ESE":   "Ost-Südost",
        "SE":    "Südost",
        "SSE":   "Süd-Südost",
        "S":     "Süd",
        "SSW":   "Süd-Südwest",
        "SW":    "Südwest",
        "WSW":   "West-Südwest",
        "W":     "West",
        "WNW":   "West-Nordwest",
        "NW":    "Nordwest",
        "NNW":   "Nord-Nordwest"
    },
    abbreviations: {
        "N":     "N",
        "NNE":   "NNO",
        "NE":    "NO",
        "ENE":   "ONO",
        "E":     "O",
        "ESE":   "OSO",
        "SE":    "SO",
        "SSE":   "SSO",
        "S":     "S",
        "SSW":   "SSW",
        "SW":    "SW",
        "WSW":   "WSW",
        "W":     "W",
        "WNW":   "WNW",
        "NW":    "NW",
        "NNW":   "NNW"
    }
}
`

kind regards andreas

**Comment by bartbutenaers** [comment]
Hi Andreas,
Thanks for the translation!
It is now available in the Node-RED palette as version ***1.0.1***.
Bart

**Comment by anderl1969** [comment]
Great, works just fine. Thx
